// <auto-generated />
using System;
using BotanikBambu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotanikBambu.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240629123440_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BotanikBambu.Models.Customerİnfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customerİnfos");
                });

            modelBuilder.Entity("BotanikBambu.Models.Orderİnfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("chairNumber")
                        .HasColumnType("int");

                    b.Property<string>("chairType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isChairAjurlu")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isTableAjurlu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("orderColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("orderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("orderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sargıColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sargıType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tableSizes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tableType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orderİnfos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Orderİnfo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BotanikBambu.Models.Truckerİnfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("OrderİnfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("deliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("receivedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("truckColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("truckPlateNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("truckType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("truckerName")
                        .HasColumnType("int");

                    b.Property<string>("truckerTelNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderİnfoId");

                    b.ToTable("Truckerİnfos");
                });

            modelBuilder.Entity("BotanikBambu.Models.Cushionİnfo", b =>
                {
                    b.HasBaseType("BotanikBambu.Models.Orderİnfo");

                    b.Property<int?>("OrderİnfoId")
                        .HasColumnType("int");

                    b.Property<string>("cushionButtonNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cushionColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("OrderİnfoId");

                    b.HasDiscriminator().HasValue("Cushionİnfo");
                });

            modelBuilder.Entity("BotanikBambu.Models.Truckerİnfo", b =>
                {
                    b.HasOne("BotanikBambu.Models.Orderİnfo", null)
                        .WithMany("Truckers")
                        .HasForeignKey("OrderİnfoId");
                });

            modelBuilder.Entity("BotanikBambu.Models.Cushionİnfo", b =>
                {
                    b.HasOne("BotanikBambu.Models.Orderİnfo", null)
                        .WithMany("Cushionİnfos")
                        .HasForeignKey("OrderİnfoId");
                });

            modelBuilder.Entity("BotanikBambu.Models.Orderİnfo", b =>
                {
                    b.Navigation("Cushionİnfos");

                    b.Navigation("Truckers");
                });
#pragma warning restore 612, 618
        }
    }
}
